apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stateless-echo
  template:
    metadata:
      labels:
        app: stateless-echo
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:1.0.0
          args: ["-text=hello", "-listen=:8080"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: stateless-echo
  labels:
    app: stateless-echo
spec:
  selector:
    app: stateless-echo
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP