# filename: job-indexed-backoff-per-index.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-backoff-per-index
  namespace: job-lab
spec:
  completions: 8
  parallelism: 4
  completionMode: Indexed
  backoffLimitPerIndex: 3
  maxFailedIndexes: 1
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: alpine:3.20
        command: ["/scripts/worker.sh"]
        env:
        - name: MODE
          value: "always_fail"
        - name: FAIL_INDEX
          value: "5"   # 5번 인덱스는 늘 실패(3회 재시도 후 실패 인덱스로 집계)
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: job-worker-scripts
          defaultMode: 0755
