# naked-pods.yaml
apiVersion: v1
kind: Pod
metadata: { name: p1, namespace: tps-demo, labels: { app: test } }
spec:
  containers: [{ name: pause, image: registry.k8s.io/pause:3.9 }]
---
apiVersion: v1
kind: Pod
metadata: { name: p2, namespace: tps-demo, labels: { app: test } }
spec:
  containers: [{ name: pause, image: registry.k8s.io/pause:3.9 }]
---
apiVersion: v1
kind: Pod
metadata: { name: p3, namespace: tps-demo, labels: { app: test } }
spec:
  containers: [{ name: pause, image: registry.k8s.io/pause:3.9 }]
---
apiVersion: v1
kind: Pod
metadata: { name: p4, namespace: tps-demo, labels: { app: test } }
spec:
  containers: [{ name: pause, image: registry.k8s.io/pause:3.9 }]

