apiVersion: v1
kind: Pod
metadata:
  name: gated-pod
  namespace: team-a
spec:
  schedulingGates:
    - name: wait.for.dependency
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - -c
        - echo ready && sleep 3600
